/* Trivia Generator Pro — built-in sample question packs.
   Each entry: [question, answer, age] where `age` is an optional audience
   band the sample-fill and Load-Sample-Game features use to respect a round's
   Age Range:
     "all"   — family / all-ages safe, evergreen knowledge
     "teen"  — fine for teens and up (a little more pop-culture / recency)
     "adult" — pub/21+ leaning references (nightlife, older or nichey topics)
   The 2-element form still works everywhere ([q, a] destructures cleanly);
   entries without a band are treated as "all". */
const TGP_SAMPLES = {
  "General Knowledge": [
    ["How many sides does a stop sign have?", "Eight", "all"],
    ["What is the largest planet in our solar system?", "Jupiter", "all"],
    ["In which city would you find the Eiffel Tower?", "Paris", "all"],
    ["How many cards are in a standard deck, not counting jokers?", "52", "all"],
    ["What do bees collect from flowers to make honey?", "Nectar", "all"],
    ["What is the capital city of Canada?", "Ottawa", "all"],
    ["What color do you get when you mix blue and yellow paint?", "Green", "all"],
    ["How many continents are there on Earth?", "Seven", "all"],
    ["What is the largest ocean on Earth?", "The Pacific Ocean", "all"],
    ["How many strings does a standard guitar have?", "Six", "all"],
    ["How many minutes are in a full day?", "1,440", "all"],
    ["Which month of the year is the shortest?", "February", "all"],
    ["What is the hardest known natural material on Earth?", "Diamond", "all"],
    ["How many degrees are in a right angle?", "90", "all"],
    ["What is the currency used in Japan?", "The yen", "all"],
    ["Roman numerals: what number does the letter 'M' represent?", "1,000", "all"],
    ["What is the tallest animal in the world?", "The giraffe", "all"],
    ["Which planet is closest to the Sun?", "Mercury", "all"],
    ["How many colors are in a rainbow?", "Seven", "all"],
    ["What is the only number that is neither prime nor composite?", "One (1)", "teen"]
  ],
  "Music": [
    ["Which pop star is known as the “Material Girl”?", "Madonna", "all"],
    ["How many keys are on a standard full-size piano?", "88", "all"],
    ["Which band recorded the album “Abbey Road”?", "The Beatles", "all"],
    ["Freddie Mercury was the lead singer of which band?", "Queen", "all"],
    ["Which country legend sang both “Jolene” and “9 to 5”?", "Dolly Parton", "all"],
    ["Which large orchestral instrument has 47 strings and 7 pedals?", "The harp", "all"],
    ["Which “King of Rock and Roll” lived at Graceland?", "Elvis Presley", "all"],
    ["Beyoncé first rose to fame as a member of which group?", "Destiny's Child", "teen"],
    ["Which rapper's real name is Marshall Mathers?", "Eminem", "teen"],
    ["“Rolling in the Deep” and “Hello” are hits by which British singer?", "Adele", "teen"],
    ["Which band recorded the classic rock staple “Hotel California”?", "Eagles", "all"],
    ["What does it mean to sing “a cappella”?", "Singing without instrumental accompaniment", "all"],
    ["How many members were in the Beatles?", "Four", "all"],
    ["Which instrument does a percussionist play?", "Drums / percussion", "all"],
    ["“Bohemian Rhapsody” was a hit for which band?", "Queen", "all"],
    ["Taylor Swift's re-recorded albums are subtitled with which two words?", "“Taylor's Version”", "teen"],
    ["Which Swedish group won Eurovision in 1974 with “Waterloo”?", "ABBA", "all"],
    ["What are the names of the two founding members of the duo Daft Punk known by — the group, that is?", "Daft Punk", "adult"],
    ["Which family group sang “I Want You Back” and “ABC”?", "The Jackson 5", "all"],
    ["A song's tempo is measured in what unit — abbreviated BPM?", "Beats per minute", "teen"]
  ],
  "Movies & TV": [
    ["Who directed both “Jaws” and “E.T.”?", "Steven Spielberg", "all"],
    ["In “The Wizard of Oz,” what does Dorothy click together three times?", "Her ruby slippers (heels)", "all"],
    ["“May the Force be with you” comes from which film franchise?", "Star Wars", "all"],
    ["What is the name of the coffee shop in the sitcom “Friends”?", "Central Perk", "teen"],
    ["Who played Jack Dawson in “Titanic”?", "Leonardo DiCaprio", "teen"],
    ["Which animated film features the song “Let It Go”?", "Frozen", "all"],
    ["In “The Simpsons,” what color is Marge's hair?", "Blue", "all"],
    ["Which actor played Iron Man in the Marvel movies?", "Robert Downey Jr.", "teen"],
    ["What kind of fish is Nemo in “Finding Nemo”?", "A clownfish", "all"],
    ["Which sitcom is set at the Dunder Mifflin Paper Company?", "The Office", "teen"],
    ["What is the name of the cowboy doll in “Toy Story”?", "Woody", "all"],
    ["Which 1993 blockbuster brought dinosaurs back to life in a theme park?", "Jurassic Park", "all"],
    ["What is the highest-grossing film franchise about a boy wizard?", "Harry Potter", "all"],
    ["In “The Lion King,” what is the name of Simba's evil uncle?", "Scar", "all"],
    ["Which streaming hit features a group of kids in the fictional town of Hawkins, Indiana?", "Stranger Things", "teen"],
    ["What are the first names of the two title characters in “Sherlock” — Holmes and …?", "Sherlock and John (Watson)", "teen"],
    ["Which movie features a character named Forrest who says “Life is like a box of chocolates”?", "Forrest Gump", "adult"],
    ["What is the name of the fictional African nation in “Black Panther”?", "Wakanda", "teen"],
    ["In “Breaking Bad,” what is the chemistry-teacher-turned-cook's first name?", "Walter (White)", "adult"],
    ["Which Pixar film takes place mostly inside a young girl's mind?", "Inside Out", "all"]
  ],
  "Sports": [
    ["How many players from one team are on a basketball court at a time?", "Five", "all"],
    ["How many holes are played in a standard round of golf?", "18", "all"],
    ["Wimbledon, the famous tennis tournament, is held in which country?", "England (the UK)", "all"],
    ["How many points is a touchdown worth, before any extra point?", "Six", "all"],
    ["In baseball, how many strikes make an out?", "Three", "all"],
    ["Which sport is played with a puck?", "Ice hockey", "all"],
    ["How often are the Summer Olympic Games held?", "Every four years", "all"],
    ["What is a perfect score in ten-pin bowling?", "300", "all"],
    ["In soccer, which player is allowed to use their hands during open play?", "The goalkeeper", "all"],
    ["How many rings are on the Olympic flag?", "Five", "all"],
    ["Which boxing legend called himself “The Greatest”?", "Muhammad Ali", "all"],
    ["In which sport would you perform a slam dunk?", "Basketball", "all"],
    ["How many players are on a soccer team on the field at one time?", "Eleven", "all"],
    ["The Tour de France is a race in which sport?", "Cycling", "all"],
    ["In tennis, what is the term for zero points?", "Love", "all"],
    ["Which country has won the most FIFA World Cups (men's)?", "Brazil", "teen"],
    ["What piece of equipment is used to hit the ball in table tennis?", "A paddle (bat)", "all"],
    ["In American football, how many yards must a team gain for a first down?", "Ten", "teen"],
    ["What color jacket is awarded to the winner of golf's Masters Tournament?", "Green", "teen"],
    ["Usain Bolt set world records in which two sprint distances?", "100m and 200m", "teen"]
  ],
  "Science & Nature": [
    ["What is the chemical symbol for gold?", "Au", "all"],
    ["Which planet is known as the Red Planet?", "Mars", "all"],
    ["What gas do plants absorb from the air to make food?", "Carbon dioxide", "all"],
    ["What is the largest mammal on Earth?", "The blue whale", "all"],
    ["How many bones are in the adult human body?", "206", "all"],
    ["What force pulls objects toward the center of the Earth?", "Gravity", "all"],
    ["What is H2O more commonly known as?", "Water", "all"],
    ["How many legs does a spider have?", "Eight", "all"],
    ["Which organ pumps blood around the body?", "The heart", "all"],
    ["What is the fastest land animal?", "The cheetah", "all"],
    ["At what temperature does water freeze, in Fahrenheit?", "32°F (0°C)", "all"],
    ["Which organs filter waste from your blood and produce urine?", "The kidneys", "all"],
    ["What is the chemical symbol for oxygen?", "O", "all"],
    ["What is the closest star to Earth?", "The Sun", "all"],
    ["What do you call an animal that eats only plants?", "A herbivore", "all"],
    ["How many hearts does an octopus have?", "Three", "teen"],
    ["What is the powerhouse of the cell?", "The mitochondria", "teen"],
    ["What is the most abundant gas in Earth's atmosphere?", "Nitrogen", "teen"],
    ["What is the study of living organisms called?", "Biology", "all"],
    ["Light travels faster than sound — true or false?", "True", "all"]
  ],
  "History": [
    ["Who was the first President of the United States?", "George Washington", "all"],
    ["In what year did the Titanic sink?", "1912", "all"],
    ["The Great Wall is located in which country?", "China", "all"],
    ["Who painted the Mona Lisa?", "Leonardo da Vinci", "all"],
    ["Which ancient civilization built the pyramids of Giza?", "The Egyptians", "all"],
    ["In which decade did World War II end?", "The 1940s (1945)", "all"],
    ["Which queen of ancient Egypt was linked to Julius Caesar and Mark Antony?", "Cleopatra", "teen"],
    ["In what year did the Berlin Wall fall?", "1989", "teen"],
    ["Who delivered the famous “I Have a Dream” speech?", "Martin Luther King Jr.", "all"],
    ["Which ship carried the Pilgrims to America in 1620?", "The Mayflower", "all"],
    ["Who is credited with inventing the telephone?", "Alexander Graham Bell", "all"],
    ["In what year was the U.S. Declaration of Independence adopted?", "1776", "all"],
    ["Who was the British Prime Minister for most of World War II?", "Winston Churchill", "teen"],
    ["Which explorer is credited with reaching the Americas in 1492?", "Christopher Columbus", "all"],
    ["The Rosetta Stone helped scholars decode which ancient writing?", "Egyptian hieroglyphs", "teen"],
    ["Who was the first man to walk on the Moon?", "Neil Armstrong", "all"],
    ["Which empire was ruled by leaders called Caesars?", "The Roman Empire", "all"],
    ["Amelia Earhart was a pioneer in which field?", "Aviation (flying)", "teen"],
    ["The Renaissance began in which country?", "Italy", "teen"],
    ["Which U.S. president was in office during the Civil War?", "Abraham Lincoln", "all"]
  ],
  "Geography": [
    ["What is traditionally considered the longest river in the world?", "The Nile", "all"],
    ["What is the smallest country in the world?", "Vatican City", "all"],
    ["Which U.S. state is the largest by area?", "Alaska", "all"],
    ["What is the capital of Australia?", "Canberra", "all"],
    ["What is the largest hot desert in the world?", "The Sahara", "all"],
    ["Mount Everest sits on the border of Nepal and which other country?", "China (Tibet)", "all"],
    ["Which European country is famously shaped like a boot?", "Italy", "all"],
    ["What is the capital of Japan?", "Tokyo", "all"],
    ["Which two countries share the world's longest international border?", "The United States and Canada", "teen"],
    ["The Amazon rainforest is mostly located in which country?", "Brazil", "all"],
    ["Which U.S. city is nicknamed “The Big Apple”?", "New York City", "all"],
    ["Which continent contains the South Pole?", "Antarctica", "all"],
    ["What is the capital of France?", "Paris", "all"],
    ["Which is the largest country in the world by area?", "Russia", "all"],
    ["What is the tallest mountain above sea level?", "Mount Everest", "all"],
    ["Which ocean is the largest?", "The Pacific", "all"],
    ["The Statue of Liberty stands in which U.S. city's harbor?", "New York City", "all"],
    ["Which country is home to the kangaroo and the koala?", "Australia", "all"],
    ["What is the capital of Egypt?", "Cairo", "teen"],
    ["Which African country was never formally colonized by a European power?", "Ethiopia", "adult"]
  ],
  "Food & Drink": [
    ["What is the main ingredient in guacamole?", "Avocado", "all"],
    ["Pizza and pasta are signature dishes of which country?", "Italy", "all"],
    ["Which spirit is the traditional base of a margarita?", "Tequila", "adult"],
    ["Sushi originated in which country?", "Japan", "all"],
    ["Which fruit is dried to make a raisin?", "A grape", "all"],
    ["Which nut is the main ingredient in marzipan?", "Almond", "all"],
    ["After water, what is the most consumed beverage in the world?", "Tea", "all"],
    ["Which vegetable is fermented to make sauerkraut?", "Cabbage", "all"],
    ["Which Italian coffee drink's name means “milk” in Italian?", "Latte (caffè latte)", "all"],
    ["Which fast-food chain is famous for the Big Mac?", "McDonald's", "all"],
    ["Honey is made by which insects?", "Bees", "all"],
    ["What are the two main fillings of a classic PB&J sandwich?", "Peanut butter and jelly", "all"],
    ["Which spirit is the base of a classic mojito?", "Rum", "adult"],
    ["What is the main ingredient in traditional hummus?", "Chickpeas", "all"],
    ["Champagne comes from which country?", "France", "adult"],
    ["What kind of pastry is used to make profiteroles and éclairs?", "Choux pastry", "teen"],
    ["Which herb is the key flavor in traditional pesto?", "Basil", "all"],
    ["A “dry” martini contains a small amount of which fortified wine?", "Vermouth", "adult"],
    ["Which country is the origin of the croissant's popularity — its national bakery symbol?", "France", "all"],
    ["What gives red velvet cake its signature color, traditionally?", "Food coloring (red dye)", "all"]
  ],
  "Word Play & Language": [
    ["What do you call a word that reads the same forwards and backwards, like “racecar”?", "A palindrome", "teen"],
    ["“Listen” and “silent” use the same letters — what is this kind of word pair called?", "An anagram", "teen"],
    ["How many letters are in the English alphabet?", "26", "all"],
    ["What is the only English word, in common lists, ending in the letters “-mt”?", "Dreamt", "adult"],
    ["A group of lions is called a what?", "A pride", "all"],
    ["What is the term for a word that sounds like the noise it describes, such as “buzz”?", "Onomatopoeia", "adult"],
    ["“Brunch” is a blend of which two words?", "Breakfast and lunch", "all"],
    ["What do you call a group of crows?", "A murder", "teen"],
    ["Which punctuation mark ends a question?", "A question mark", "all"],
    ["What is the longest word you can type using only the top row of a keyboard — a common answer?", "Typewriter", "adult"],
    ["A word that means the opposite of another is called a what?", "An antonym", "all"],
    ["What is the plural of “goose”?", "Geese", "all"],
    ["Which single word can mean both a flying mammal and a piece of baseball equipment?", "Bat", "all"],
    ["What do you call a comparison using “like” or “as”?", "A simile", "teen"],
    ["The abbreviation “etc.” is short for which Latin phrase?", "Et cetera", "all"],
    ["What is a seven-letter word for a word with the same meaning as another?", "Synonym", "all"],
    ["Which language has the most native speakers in the world?", "Mandarin Chinese", "teen"],
    ["What do you call a made-up word formed from initials, like NASA or SCUBA?", "An acronym", "teen"],
    ["“Smog” is a blend of which two words?", "Smoke and fog", "all"],
    ["How many letters in the word “alphabet”?", "Eight", "all"]
  ],
  "Logos, Brands & Slogans": [
    ["“Just Do It” is the slogan of which sportswear brand?", "Nike", "all"],
    ["Which tech company's logo is an apple with a bite taken out of it?", "Apple", "all"],
    ["“I'm Lovin' It” is the slogan of which fast-food chain?", "McDonald's", "all"],
    ["Which brand's logo features golden arches?", "McDonald's", "all"],
    ["The three-pointed star inside a circle is the logo of which car maker?", "Mercedes-Benz", "teen"],
    ["Which delivery/logistics company's logo hides an arrow between the E and x?", "FedEx", "adult"],
    ["“Red Bull gives you …” what?", "Wings", "teen"],
    ["Which coffee chain has a green twin-tailed mermaid (siren) as its logo?", "Starbucks", "all"],
    ["The “tick” or “swoosh” is the logo of which company?", "Nike", "all"],
    ["Which social platform's logo is a white bird — before its rebrand to “X”?", "Twitter", "teen"],
    ["“Finger Lickin' Good” is associated with which fried-chicken chain?", "KFC", "all"],
    ["Which car brand uses four interlocking rings as its logo?", "Audi", "teen"],
    ["Which soft drink uses the slogan “Taste the Feeling” and a red-and-white script logo?", "Coca-Cola", "all"],
    ["The bitten-lips-and-tongue logo belongs to which rock band?", "The Rolling Stones", "adult"],
    ["Which shipping-and-retail giant's logo has an arrow from A to Z?", "Amazon", "all"],
    ["“Think Different” was a famous slogan for which company?", "Apple", "adult"],
    ["Which fast-food chain's mascot is a red-haired girl named after the founder's daughter?", "Wendy's", "teen"],
    ["The “golden shell” (pecten) is the logo of which oil company?", "Shell", "teen"],
    ["Which brand's slogan is “Because You're Worth It”?", "L'Oréal", "adult"],
    ["A blue bird formerly, now a black X — what is the app now called?", "X (formerly Twitter)", "teen"]
  ]
};

/* Numeric tiebreakers — closest answer wins. */
const TGP_TIEBREAKERS = [
  ["How many feet tall is the Statue of Liberty, heel to torch?", "151 feet"],
  ["What is the height of Mount Everest in feet?", "29,032 feet"],
  ["In what year did the first iPhone go on sale?", "2007"],
  ["In what year did Disneyland open in California?", "1955"],
  ["How many seats are in the U.S. House of Representatives?", "435"],
  ["How many minutes long is the movie “Titanic” (1997)?", "195 minutes"],
  ["How many bones are in the adult human body?", "206"],
  ["How many countries are members of the United Nations?", "193"],
  ["How many keys are on a standard full-size piano?", "88"],
  ["In what year did the Berlin Wall fall?", "1989"]
];
